name: Build container

on:
  - push
  - pull_request

jobs:
  build-application-inside-container:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker build -t cameraapp . && docker --rm -it -v $PWD:/work -w /work cameraapp julia --project=. -e 'using Pkg; Pkg.instantiate(); include("build.jl")'
